name: Build & Deploy

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - run: npm ci
    - run: npm run build
    # - run: npm test
    #   env:
    #     CI: true
    - name: Upload Pages artifact
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

